markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Wes Vetter
url: http://wesvetter.com
description: this is my blog where I blog things.
twitter: wesvetter
github: wesvetter
gravatar_url: http://www.gravatar.com/avatar/dfc9bad6f80244b7b64e630ee0bd6e8d.png
